#!/usr/bin/env bash
# The shebang line specifies the path to the Bash interpreter.

# The script starts the loop here
while true
do
  # Inside the loop, it prints the phrase "To infinity and beyond"
  echo "To infinity and beyond"
  
  # Then it sleeps for 2 seconds
  sleep 2
done
# The loop repeats indefinitely because the condition 'true' always evaluates to true.

