#!/bin/bash

# Check if the process 7-highlander is running
if pgrep -x "7-highlander" > /dev/null
then
    # Kill the process
    pkill -x "7-highlander"
    echo "Process 7-highlander has been killed"
else
    echo "Process 7-highlander is not running"
fi

